name: Run Tests on Dispatch

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: pip install -r requirements.txt

      - name: Run tests
        id: pytest
        run: |
          mkdir -p results
          pytest tests/api --junitxml=results/report.xml || echo "Tests failed"

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: results/report.xml

      - name: Notify Slack
        if: always() # garante que a notificação rode mesmo se os testes falharem
        run: |
          STATUS="SUCCESSFUL"
          FAILS=$(grep 'failures=' results/report.xml | sed -n 's/.*failures="\([0-9]*\)".*/\1/p')
          if [ "$FAILS" != "0" ]; then
            STATUS="FAILED"
          fi
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"QA Tests finished with status: $STATUS\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
